AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Personal website with server-side rendering using Vike and React deployed with Lambda@Edge

Globals:
  Function:
    Timeout: 30
    MemorySize: 512
    Environment:
      Variables:
        NODE_ENV: production

Resources:
  # Lambda@Edge function for SSR
  PersonalWebsiteFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: dist/server/index.handler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      AutoPublishAlias: live
      Environment:
        Variables:
          NODE_ENV: production
      # Lambda@Edge functions must be deployed to us-east-1
      # and referenced from CloudFront by version/alias
      FunctionUrlConfig:
        AuthType: NONE
        Cors:
          AllowOrigins:
            - '*'
          AllowMethods:
            - GET
            - POST
            - HEAD
            - OPTIONS
          AllowHeaders:
            - '*'
      Role: !GetAtt PersonalWebsiteFunctionRole.Arn

  # IAM Role for the Lambda@Edge function
  PersonalWebsiteFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
                - edgelambda.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'

  # S3 bucket for static assets
  StaticAssets:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html

  # Bucket policy to allow public reading of static assets
  StaticAssetsBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref StaticAssets
      PolicyDocument:
        Statement:
          - Action: s3:GetObject
            Effect: Allow
            Resource: !Sub "${StaticAssets.Arn}/*"
            Principal: "*"

  # CloudFront distribution that uses Lambda@Edge
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - Id: S3Static
            DomainName: !GetAtt StaticAssets.DomainName
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: http-only
        Enabled: true
        DefaultCacheBehavior:
          TargetOriginId: S3Static
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods: [GET, HEAD, OPTIONS]
          CachedMethods: [GET, HEAD]
          ForwardedValues:
            QueryString: true
            Cookies:
              Forward: none
            Headers:
              - Host
          LambdaFunctionAssociations:
            - EventType: origin-request
              LambdaFunctionARN: !Ref PersonalWebsiteFunctionVersion
        CacheBehaviors:
          - PathPattern: "/assets/*"
            TargetOriginId: S3Static
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods: [GET, HEAD, OPTIONS]
            CachedMethods: [GET, HEAD]
            ForwardedValues:
              QueryString: false
              Cookies:
                Forward: none
            Compress: true
            DefaultTTL: 31536000  # 1 year
            MinTTL: 31536000
            MaxTTL: 31536000
        DefaultRootObject: ""
        PriceClass: PriceClass_100
        HttpVersion: http2
        ViewerCertificate:
          CloudFrontDefaultCertificate: true
        CustomErrorResponses:
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html

  # Get a specific version of the Lambda function to use in CloudFront
  PersonalWebsiteFunctionVersion:
    Type: AWS::Lambda::Version
    Properties:
      FunctionName: !Ref PersonalWebsiteFunction
      Description: Version for Lambda@Edge

Outputs:
  PersonalWebsiteFunction:
    Description: "Personal Website Lambda Function ARN"
    Value: !GetAtt PersonalWebsiteFunction.Arn
  PersonalWebsiteFunctionVersion:
    Description: "Personal Website Lambda Function Version ARN for Lambda@Edge"
    Value: !Ref PersonalWebsiteFunctionVersion
  CloudFrontDistributionDomainName:
    Description: "CloudFront Distribution Domain Name"
    Value: !GetAtt CloudFrontDistribution.DomainName
  StaticAssetsS3BucketName:
    Description: "S3 Bucket for Static Assets"
    Value: !Ref StaticAssets