AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Personal website with server-side rendering using Vike and React deployed with Lambda@Edge

Parameters:
  CodeHash:
    Type: String
    Description: Hash of the Lambda function code (used to determine if a new version is needed)
    Default: '0000000000'
  Environment:
    Type: String
    Description: Environment to deploy to (dev, staging, prod)
    Default: 'prod'
    AllowedValues:
      - dev
      - staging
      - prod
  SiteDomain:
    Type: String
    Description: Custom domain for the website (e.g., example.com)
    Default: 'johnmollberg.com'
  HostedZoneId:
    Type: String
    Description: Route53 Hosted Zone ID
    Default: 'Z2P8S248LOC4KP'

Globals:
  Function:
    Timeout: 30
    MemorySize: 512

Resources:
  # Lambda@Edge function for SSR
  PersonalWebsiteFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./dist/server
      Handler: index.handler
      Runtime: nodejs22.x  # Using latest Node.js 22.x runtime
      FunctionName: !Sub "personal-website-${Environment}-ssr"
      Architectures:
        - x86_64
      # Lambda@Edge functions must be deployed to us-east-1
      # and referenced from CloudFront by version/alias
      # NOTE: Lambda@Edge functions cannot have environment variables
      # We'll use a hardcoded secret name in the code instead
      Timeout: 5  # Lambda@Edge has a maximum timeout of 5 seconds for origin-request
      MemorySize: 1024  # Increased memory for better performance
      FunctionUrlConfig:
        AuthType: NONE
        Cors:
          AllowOrigins:
            - '*'
          AllowMethods:
            - GET
            - POST
            - HEAD
          AllowHeaders:
            - '*'
      Role: !GetAtt PersonalWebsiteFunctionRole.Arn

  # IAM Role for the Lambda@Edge function
  PersonalWebsiteFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
                - edgelambda.amazonaws.com
                - cloudfront.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
        - 'arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess'
      Policies:
        - PolicyName: LambdaEdgeExecutionPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource: 'arn:aws:logs:*:*:*'
              - Effect: Allow
                Action: 
                  - 'lambda:GetFunction'
                  - 'lambda:EnableReplication*'
                  - 'iam:CreateServiceLinkedRole'
                  - 'cloudfront:UpdateDistribution'
                Resource: '*'
              - Effect: Allow
                Action:
                  - 'secretsmanager:GetSecretValue'
                  - 'secretsmanager:DescribeSecret'
                Resource: 
                  - !Sub 'arn:aws:secretsmanager:us-east-1:${AWS::AccountId}:secret:${Environment}/statsig-server-secret-??????'
              - Effect: Allow
                Action: 
                  - 's3:GetObject'
                  - 's3:ListBucket'
                Resource:
                  - !Sub 'arn:aws:s3:::${StaticAssets}/*'
                  - !Sub 'arn:aws:s3:::${StaticAssets}'

  # S3 bucket for CloudFront access logs
  LoggingBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: !Sub "personal-website-logs-${Environment}-${AWS::AccountId}"
      VersioningConfiguration:
        Status: Suspended
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerPreferred
      LifecycleConfiguration:
        Rules:
          - Id: DeleteLogsAfter30Days
            Status: Enabled
            ExpirationInDays: 30
  
  # Log delivery permissions using a bucket ACL
  LoggingBucketBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref LoggingBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: logging.s3.amazonaws.com
            Action: 
              - s3:PutObject
            Resource: !Sub "arn:aws:s3:::${LoggingBucket}/*"
          - Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: 
              - s3:GetBucketAcl
              - s3:PutBucketAcl
            Resource: !Sub "arn:aws:s3:::${LoggingBucket}"

  # S3 bucket for static assets
  StaticAssets:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "personal-website-assets-${Environment}-${AWS::AccountId}"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      WebsiteConfiguration:
        IndexDocument: index.html
        # Removed ErrorDocument to allow proper 404 handling
      OwnershipControls:
        Rules:
          - ObjectOwnership: ObjectWriter

  # Bucket policy to allow public reading of static assets
  StaticAssetsBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref StaticAssets
      PolicyDocument:
        Statement:
          - Action: s3:GetObject
            Effect: Allow
            Resource: !Sub "${StaticAssets.Arn}/*"
            Principal: "*"

  # CloudFront distribution that uses Lambda@Edge
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      Tags:
        - Key: Environment
          Value: !Ref Environment
      DistributionConfig:
        Origins:
          - Id: S3Static
            DomainName: !GetAtt StaticAssets.DomainName
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: http-only
        Enabled: true
        Logging:
          Bucket: !GetAtt LoggingBucket.DomainName
          Prefix: 'cloudfront-logs/'
          IncludeCookies: false
        DefaultCacheBehavior:
          TargetOriginId: S3Static
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods: [GET, HEAD, OPTIONS]
          CachedMethods: [GET, HEAD]
          ForwardedValues:
            QueryString: true
            Cookies:
              Forward: all
            Headers:
              - Host
              - Origin
              - Referer
              - User-Agent
          Compress: true
          DefaultTTL: 0
          MinTTL: 0
          MaxTTL: 0
          LambdaFunctionAssociations:
            - EventType: origin-request
              LambdaFunctionARN: !Ref PersonalWebsiteFunctionVersion
        CacheBehaviors:
          - PathPattern: "/assets/*"
            TargetOriginId: S3Static
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods: [GET, HEAD, OPTIONS]
            CachedMethods: [GET, HEAD]
            ForwardedValues:
              QueryString: false
              Cookies:
                Forward: none
            Compress: true
            DefaultTTL: 31536000  # 1 year
            MinTTL: 31536000
            MaxTTL: 31536000
          - PathPattern: "/favicon.ico"
            TargetOriginId: S3Static
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods: [GET, HEAD, OPTIONS]
            CachedMethods: [GET, HEAD]
            ForwardedValues:
              QueryString: false
              Cookies:
                Forward: none
            Compress: true
            DefaultTTL: 86400  # 1 day
            MinTTL: 86400
            MaxTTL: 86400
        DefaultRootObject: ""
        PriceClass: PriceClass_100
        HttpVersion: http2
        Aliases:
          - !Ref SiteDomain
        ViewerCertificate:
          AcmCertificateArn: !Ref SiteCertificate
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021
        CustomErrorResponses:
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html
          # Removed 404 error response override to allow proper 404 handling

  # Get a specific version of the Lambda function to use in CloudFront
  # New versions are only created when the code hash changes
  PersonalWebsiteFunctionVersion:
    Type: AWS::Lambda::Version
    Properties:
      FunctionName: !Ref PersonalWebsiteFunction
      Description: !Sub "Version for Lambda@Edge in ${Environment} environment - CodeHash: ${CodeHash}"
      # The Code Hash in the description ensures new versions are only created when the code changes
      
  # ACM Certificate with automatic DNS validation
  SiteCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref SiteDomain
      SubjectAlternativeNames:
        - !Ref SiteDomain  # Include both apex and www domains if needed
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName: !Ref SiteDomain
          HostedZoneId: !Ref HostedZoneId
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Name
          Value: !Sub "${SiteDomain} Certificate"
        
  # Route 53 record to point domain to CloudFront
  Route53CloudFrontRecord:
    Type: AWS::Route53::RecordSet
    DependsOn: CloudFrontDistribution
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref SiteDomain
      Type: A
      AliasTarget:
        DNSName: !GetAtt CloudFrontDistribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2 # CloudFront's hosted zone ID (constant value)


Outputs:
  PersonalWebsiteFunction:
    Description: "Personal Website Lambda Function ARN"
    Value: !GetAtt PersonalWebsiteFunction.Arn
  PersonalWebsiteFunctionVersion:
    Description: "Personal Website Lambda Function Version ARN for Lambda@Edge"
    Value: !Ref PersonalWebsiteFunctionVersion
  CloudFrontDistributionDomainName:
    Description: "CloudFront Distribution Domain Name"
    Value: !GetAtt CloudFrontDistribution.DomainName
  StaticAssetsS3BucketName:
    Description: "S3 Bucket for Static Assets"
    Value: !Ref StaticAssets
  SiteDomainName:
    Description: "Custom Site Domain"
    Value: !Ref SiteDomain
  CertificateARN:
    Description: "ACM Certificate ARN"
    Value: !Ref SiteCertificate